version: "3.9"
services:
  mqtt-broker:
    image: 'eclipse-mosquitto'
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - ./mqtt-broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mqtt-broker/users:/mosquitto/config/users
      - mqtt-data:/mosquitto/data 
      - mqtt-logs:/mosquitto/log
    healthcheck:
      test:
        [
          "CMD",
          "mosquitto_pub",
          "-h",
          "localhost",
          "-p",
          "1883",
          "-u",
          "iot-device",
          "-P",
          "10060509",
          "-t",
          "test",
          "-m",
          "testing"
        ]
      timeout: 5s
      retries: 3
  gateway-cloud-broker:
    image: 'eclipse-mosquitto'
    ports:
      - '1884:1884'
    volumes:
      - ./gateway-cloud-broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./gateway-cloud-broker/users:/mosquitto/config/users
      - mqtt-data:/mosquitto/data 
      - mqtt-logs:/mosquitto/log
    healthcheck:
      test:
        [
          "CMD",
          "mosquitto_pub",
          "-h",
          "localhost",
          "-p",
          "1883",
          "-u",
          "iot-device",
          "-P",
          "10060509",
          "-t",
          "test",
          "-m",
          "testing"
        ]
      timeout: 5s
      retries: 3
  sensors:
    image: 'sensors'
    stdin_open: true
    tty: true
    environment:
      - TZ=Europe/Belgrade
    volumes:
      - ./sensors/sensor_conf.json:/app/sensor_conf.json
    depends_on:
      mqtt-broker:
        condition: service_healthy
  postgresql-db:
    image: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s 
    environment:
       POSTGRES_DB: iot-platform-database
       PGUSER: postgres
       POSTGRES_PASSWORD: mysecretpassword
  iot-cloud-platform:
    image: 'iot-cloud-platform'
    ports:
      - '8080:8080'
    env_file:
      - iot-platform/.env
    environment:
      - TZ=Europe/Belgrade
    depends_on:
        postgresql-db:
          condition: service_healthy
  iot-gateway:
    image: 'iot-gateway'
    ports:
      - '9876:9876'
    stdin_open: true
    tty: true
    volumes:
      - ./iot-gateway/configuration/app_conf.json:/app/configuration/app_conf.json
    environment:
      - TZ=Europe/Belgrade
    depends_on:
      iot-cloud-platform:
        condition: service_started
      mqtt-broker:
        condition: service_healthy
  dashboard:
    image: 'iot-dashboard'
    ports:
      - '3000:3000'
    env_file:
      - iot-dashboard/.env
    depends_on:
      iot-cloud-platform:
        condition: service_started
volumes:
  mqtt-data:
  mqtt-logs:
  db-data:
