name: Code Quality

on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master
  workflow_dispatch:

jobs:
  lint:
    name: Python Code Quality and Lint
    runs-on: ubuntu-latest

    steps:
      - uses: parafoxia/pip-install@v1
        with:
          packages: flake8-docstrings
      - uses: actions/checkout@v2
      - uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "src"
          use-pylint: false
          use-pycodestyle: true
          use-flake8: true
          use-black: false
          use-mypy: false
          use-isort: false
          extra-pylint-options: "--max-line-length=120 --ignore=E722,W0703,E0401,W0107"
          extra-pycodestyle-options: "--max-line-length=120 --ignore=E722"
          extra-flake8-options: "--docstring-convention numpy"
          extra-black-options: ""
          extra-mypy-options: ""
          extra-isort-options: ""